export class Users {
    public userList = [
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart', 'Pictorial slice shape', 'Animated gauge blue'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Pictorial Slice Shape', 'Animated Gauge Blue'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },

        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },

        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },

        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },

        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            name: 'Vimalathithan',
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        }
    ]
}
