export class Users {
    public userList = [
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal1",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera1",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal1",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera1",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },,
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal1",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera1",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal1",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera1",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },
        {
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        },{
            id: "1",
            username: "Vimal",
            password: "vimal",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            input: "5V"
        }
    ]
}
