import { GaugeChart } from "@amcharts/amcharts4/charts";
import { IndicatorGaugeComponent } from "../components/indicator-gauge/indicator-gauge.component";

export class Users {
    public userList = [
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart', 'Pictorial slice shape', 'Animated gauge blue'],
            input: "3A"
        },
        {
            id: "1",
            username: "Saral",
            name: 'Krish',
            password: "saral",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Speedometer', 'Tachometer', 'Intake Air Temperature', 'Absolute Barometric Pressure','Battery','Engine Coolant Temperature','Intake Manifold Absolute Pressure','Air Flow Rate','Throttle Position'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Pictorial slice shape', 'Animated gauge blue'],
            input: "5V"
        },
        {
            id: "3",
            username: "Joseph",
            name: "DJ",
            password: "joseph",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['indicator gauge','temperature-gauge'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },

        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },{
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },

        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },{
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },

        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },{
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },

        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        },
        {
            id: "1",
            username: "KRISHTEC",
            name: 'Krish',
            password: "krishteccbe",
            company: "Krish tec",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "Admin",
            device: "Ammeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "3A"
        },
        {
            id: "2",
            username: "Veera",
            name: "Veerapandian",
            password: "veera",
            company: "moonraft",
            contact: "1234567890",
            email: "abc@gmail.com",
            role: "User",
            device: "Voltmeter",
            chart: ['Animated gauge', 'Pictorial chart'],
            input: "5V"
        }
    ]
}
